# Generated by Django 5.2.8 on 2025-11-12 08:39

import MainApplication.Post.post_models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0002_post_postcomment_postlike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='content_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='flagged_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to='posts/images/%Y/%m/%d/', validators=[MainApplication.Post.post_models.validate_image_size, MainApplication.Post.post_models.validate_image_format, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_safe', models.BooleanField(default=True)),
                ('moderation_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MainApplication.post')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
