# Generated by Django 5.2.8 on 2025-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0003_remove_post_image_post_content_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, null=True),
        ),
    ]
